<bug id='32250' author='DavidKWH' open_date='2019-09-05T18:36:30Z' closed_time='2019-09-11T17:28:52Z'>
	<summary>tf.saved_model.save() broken for my subclassed model in tf-2.0.0rc0</summary>
	<description>
Please make sure that this is a bug. As per our GitHub Policy, we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template
System information

Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04.02 LTS
Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
TensorFlow installed from (source or binary): binary
TensorFlow version (use command below): tf2.0.0rc0
Python version: 3.6.7
Bazel version (if compiling from source):
GCC/Compiler version (if compiling from source):
CUDA/cuDNN version: N/A
GPU model and memory: N/A

You can collect some of this information using our environment capture
&lt;denchmark-link:https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh&gt;script&lt;/denchmark-link&gt;

You can also obtain the TensorFlow version with: 1. TF 1.0:  2. TF 2.0: 
n [4]: tf.version.GIT_VERSION
Out[4]: 'v2.0.0-beta1-5101-gc75bb66'
In [5]: tf.version.VERSION
Out[5]: '2.0.0-rc0'
Describe the current behavior
I have a subclassed model that I have been saving and deploying since tf-2.0.0b0 and after upgrading to rc0, it errored out with this message.
[save.py:136] Skipping full serialization of object &lt;main.MyModel object at 0x7f76815add30&gt; because an error occurred while tracing layer functions. Error message: in converted code:
TypeError: tf__call() takes from 2 to 3 positional arguments but 4 were given
This is how the call method is defined in my class.  Can someone tell me what went wrong, or what I need to change to make this work?
Thanks, David
class MyModel(Model):
&lt;denchmark-code&gt;def __init__(self, n_layers, h_dim, b_dim,
                   activation_fn,
                   kernel_init,
                   batch_norm):
    super().__init__()
    ... skipping ...

@tf.function
def call(self, inputs, training=False):
    y = inputs[0]
    h = inputs[1]
    n_var = inputs[2]
    x = layers.concatenate([y, h])
    if self.n_layers &gt;= 1: x = self.d_hidden_1(x,training=training)
    if self.n_layers &gt;= 2: x = self.d_hidden_2(x,training=training)
    if self.n_layers &gt;= 3: x = self.d_hidden_3(x,training=training)
    if self.n_layers &gt;= 4: x = self.d_hidden_4(x,training=training)
    if self.n_layers &gt;= 5: x = self.d_hidden_5(x,training=training)
    # scale output by 1/n_var
    #return self.d_out(x) / n_var
    return self.d_out(x,training=training)
&lt;/denchmark-code&gt;

Describe the expected behavior
It should just work
Code to reproduce the issue
Provide a reproducible test case that is the bare minimum necessary to generate the problem.
See above
Other info / logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.
	</description>
	<comments>
		<comment id='1' author='DavidKWH' date='2019-09-05T22:18:27Z'>
		&lt;denchmark-link:https://github.com/DavidKWH&gt;@DavidKWH&lt;/denchmark-link&gt;
 Can you please assemble a minimal reproducible code snippet to reflect this issue? Thanks!
		</comment>
		<comment id='2' author='DavidKWH' date='2019-09-06T17:23:44Z'>
		This has been resolved in the discuss forum.  It has been reproduced and a fixed has been proposed by Kathy.  Please see
&lt;denchmark-link:https://groups.google.com/a/tensorflow.org/forum/#!topic/discuss/wlwLvWnD4BI&gt;https://groups.google.com/a/tensorflow.org/forum/#!topic/discuss/wlwLvWnD4BI&lt;/denchmark-link&gt;

		</comment>
		<comment id='3' author='DavidKWH' date='2019-09-10T18:21:30Z'>
		This issue has been resolved in the nightly and cherrypicked to the 2.0 branch. Please let us know if it is ok to close the issue.
Thanks!
		</comment>
		<comment id='4' author='DavidKWH' date='2019-09-11T17:28:52Z'>
		Closing issue, please feel free to reopen if you continue to see issues.
		</comment>
		<comment id='5' author='DavidKWH' date='2019-09-11T17:28:53Z'>
		Are you satisfied with the resolution of your issue?
&lt;denchmark-link:https://docs.google.com/forms/d/e/1FAIpQLSfaP12TRhd9xSxjXZjcZFNXPGk4kc1-qMdv3gc6bEP90vY1ew/viewform?entry.85265664=Yes&amp;entry.2137816233=32250&gt;Yes&lt;/denchmark-link&gt;

&lt;denchmark-link:https://docs.google.com/forms/d/e/1FAIpQLSfaP12TRhd9xSxjXZjcZFNXPGk4kc1-qMdv3gc6bEP90vY1ew/viewform?entry.85265664=No&amp;entry.2137816233=32250&gt;No&lt;/denchmark-link&gt;

		</comment>
	</comments>
</bug>