<bug id='1040' author='BlackHC' open_date='2020-05-15T11:57:04Z' closed_time='2020-05-16T16:54:46Z'>
	<summary>gpu_info crashes because it cannot parse "N/A"</summary>
	<description>
&lt;denchmark-h:h2&gt;üêõ Bug description&lt;/denchmark-h&gt;

When trying to use gpu_info, it throws:
&lt;denchmark-code&gt; File "/home/blackhc/anaconda3/envs/hello-mnist/lib/python3.7/site-packages/ignite/contrib/metrics/gpu_info.py", line 91, in completed
    engine.state.metrics[util_name] = int(util_report['gpu_util'])
ValueError: invalid literal for int() with base 10: 'N/A'
&lt;/denchmark-code&gt;

There is error handling code above it, but it does not catch the issue ("N/A" is returned).
I assume my GPU does not support it. However, it would be neat to have a graceful failure mode.
Thank you!
Andreas
&lt;denchmark-h:h2&gt;Environment&lt;/denchmark-h&gt;

torch 1.5 on a GTX 780 TI (source)
ignite 0.3.0 (conda)
pynvml 8.0.4 (pip)
	</description>
	<comments>
		<comment id='1' author='BlackHC' date='2020-05-15T12:00:00Z'>
		Hi Andreas, thanks for catching that !
Maybe, we can cast it to -1 or 0 if no support of gpu_util.
Actually, what shows nvidia-smi on your GPU ?
		</comment>
		<comment id='2' author='BlackHC' date='2020-05-16T17:58:26Z'>
		Thank you! And sorry for the reply! nvidia-smi also displays N/A
		</comment>
	</comments>
</bug>