<bug id='18193' author='sxjscience' open_date='2020-04-29T16:00:22Z' closed_time='2020-05-20T21:58:48Z'>
	<summary>[Bug][Numpy] Very basic functionality of Gluon is broken</summary>
	<description>
After &lt;denchmark-link:https://github.com/apache/incubator-mxnet/pull/17283&gt;#17283&lt;/denchmark-link&gt;
, the following very basic example of gluon is broken:
import mxnet as mx
mx.npx.set_np()
from mxnet.gluon import nn
net = nn.Dense(16, in_units=16)
net.initialize()
out = net(mx.np.ones((32, 16)))
out.asnumpy()
&lt;denchmark-code&gt;~/mxnet/python/mxnet/numpy/random.py in uniform(low, high, size, dtype, ctx, out)
    135     inequality condition.
    136     """
--&gt; 137     return _mx_nd_np.random.uniform(low, high, size=size, ctx=ctx, dtype=dtype, out=out)
    138 
    139 

~/mxnet/python/mxnet/ndarray/numpy/random.py in uniform(low, high, size, dtype, ctx, out)
    135     if size == ():
    136         size = None
--&gt; 137     return _api_internal.uniform(low, high, size, ctx, dtype, out)
    138 
    139 

~/mxnet/python/mxnet/_ffi/_ctypes/function.py in __call__(self, *args)
    113                 self.handle, values, tcodes, ctypes.c_int(num_args),
    114                 ctypes.byref(ret_val), ctypes.byref(ret_tcode)) != 0:
--&gt; 115             raise get_last_ffi_error()
    116         _ = temp_args
    117         _ = args

MXNetError: Traceback (most recent call last):
  File "../src/imperative/./imperative_utils.h", line 251
MXNetError: Check failed: outputs[i]-&gt;dtype() == out_types[i] (0 vs. 1) : 0-th output has invalid dtype. Expecting 1 got 0 in operator _npi_uniform
&lt;/denchmark-code&gt;

	</description>
	<comments>
		<comment id='1' author='sxjscience' date='2020-04-29T16:01:36Z'>
		&lt;denchmark-link:https://github.com/yzhliu&gt;@yzhliu&lt;/denchmark-link&gt;
 &lt;denchmark-link:https://github.com/JiangZhaoh&gt;@JiangZhaoh&lt;/denchmark-link&gt;
 &lt;denchmark-link:https://github.com/szha&gt;@szha&lt;/denchmark-link&gt;

		</comment>
		<comment id='2' author='sxjscience' date='2020-04-29T22:31:15Z'>
		Assignee: &lt;denchmark-link:https://github.com/JiangZhaoh&gt;@JiangZhaoh&lt;/denchmark-link&gt;

		</comment>
		<comment id='3' author='sxjscience' date='2020-04-29T23:55:54Z'>
		Sorry for that. I'll fix it as soon as possible.
		</comment>
		<comment id='4' author='sxjscience' date='2020-04-30T00:04:19Z'>
		which tests were supposed to catch this issue?
		</comment>
		<comment id='5' author='sxjscience' date='2020-04-30T00:07:17Z'>
		&lt;denchmark-link:https://github.com/szha&gt;@szha&lt;/denchmark-link&gt;
 For example, 
 I think there are tests in  that will capture this.
		</comment>
		<comment id='6' author='sxjscience' date='2020-04-30T00:50:48Z'>
		That's my issue. In order to not effect original tests, I didn't change the decorator "use_np", which still use return use_np_shape(use_np_array(func)). But in npx.set_np() I default flag dtype as True and then set_np_default_dtype(dtype).
Details in /mxnet/python/mxnet/util.py
		</comment>
		<comment id='7' author='sxjscience' date='2020-04-30T00:52:20Z'>
		OK, so this is not related to CI.
		</comment>
		<comment id='8' author='sxjscience' date='2020-04-30T02:37:01Z'>
		I have found the reason. It because set_np() only change the mxnet.numpy functions to default dtype as float64, but doesn't effect mxnet.ndarray functions which still default float32.
The issue mentioned above just like this code:
&lt;denchmark-code&gt;&gt;&gt;&gt; import mxnet
&gt;&gt;&gt; from mxnet import numpy as np
&gt;&gt;&gt; from mxnet import ndarray as nd
&gt;&gt;&gt; from mxnet import npx
&gt;&gt;&gt; npx.set_np()
&gt;&gt;&gt; a = nd.zeros(5)
&gt;&gt;&gt; a.dtype
&lt;class 'numpy.float32'&gt;
&gt;&gt;&gt; np.random.uniform(low = -1, high = 1, size = (5), out = a)
Traceback (most recent call last):
  File "&lt;stdin&gt;", line 1, in &lt;module&gt;
  File "/home/ubuntu/mxnet/python/mxnet/numpy/random.py", line 137, in uniform
    return _mx_nd_np.random.uniform(low, high, size=size, ctx=ctx, dtype=dtype, out=out)
  File "/home/ubuntu/mxnet/python/mxnet/ndarray/numpy/random.py", line 145, in uniform
    return _api_internal.uniform(low, high, size, ctx, dtype, out)
  File "mxnet/_ffi/_cython/./function.pxi", line 188, in mxnet._ffi._cy3.core.FunctionBase.__call__
  File "mxnet/_ffi/_cython/./function.pxi", line 133, in mxnet._ffi._cy3.core.FuncCall
  File "mxnet/_ffi/_cython/./base.pxi", line 90, in mxnet._ffi._cy3.core.CALL
mxnet.base.MXNetError: Traceback (most recent call last):
  File "../src/imperative/./imperative_utils.h", line 251
MXNetError: Check failed: outputs[i]-&gt;dtype() == out_types[i] (0 vs. 1) : 0-th output has invalid dtype. Expecting 1 got 0 in operator _npi_uniform
&gt;&gt;&gt; npx.set_np(dtype = False)
&gt;&gt;&gt; np.random.uniform(low = -1, high = 1, size = (5), out = a)
[0.09762704 0.18568921 0.43037868 0.6885315  0.20552671]
&lt;NDArray 5 @cpu(0)&gt;
&lt;/denchmark-code&gt;

So, I think I'd better not to set dtype=True flag in npx.set_np(), seperate this flag along in a single function npx.set_numpy_default_dtype() instead. Or if there any other better solutions, please tell me.
		</comment>
		<comment id='9' author='sxjscience' date='2020-04-30T03:17:18Z'>
		I think one of the root cause is that gluon optimizer and initializer are still using the legacy NDArray. We should fix that.

Get Outlook for iOS&lt;&lt;denchmark-link:https://aka.ms/o0ukef&gt;https://aka.ms/o0ukef&lt;/denchmark-link&gt;
&gt;
________________________________
From: JiangZhaoh &lt;notifications@github.com&gt;
Sent: Wednesday, April 29, 2020 7:37:14 PM
To: apache/incubator-mxnet &lt;incubator-mxnet@noreply.github.com&gt;
Cc: Xingjian SHI &lt;xshiab@connect.ust.hk&gt;; Author &lt;author@noreply.github.com&gt;
Subject: Re: [apache/incubator-mxnet] [Bug][Numpy] Very basic functionality of Gluon is broken (&lt;denchmark-link:https://github.com/apache/incubator-mxnet/issues/18193&gt;#18193&lt;/denchmark-link&gt;
)


I have found the reason. It because set_np() only change the mxnet.numpy functions to default dtype as float64, but doesn't effect mxnet.ndarray functions which still default float32.
The issue mentioned above just like this code:
&gt;&gt; import mxnet
&gt;&gt; from mxnet import numpy as np
&gt;&gt; from mxnet import ndarray as nd
&gt;&gt; from mxnet import npx
&gt;&gt; npx.set_np()
&gt;&gt; a = nd.zeros(5)
&gt;&gt; a.dtype
&lt;class 'numpy.float32'&gt;
&gt;&gt; np.random.uniform(low = -1, high = 1, size = (5), out = a)
Traceback (most recent call last):
  File "&lt;stdin&gt;", line 1, in &lt;module&gt;
  File "/home/ubuntu/mxnet/python/mxnet/numpy/random.py", line 137, in uniform
    return _mx_nd_np.random.uniform(low, high, size=size, ctx=ctx, dtype=dtype, out=out)
  File "/home/ubuntu/mxnet/python/mxnet/ndarray/numpy/random.py", line 145, in uniform
    return _api_internal.uniform(low, high, size, ctx, dtype, out)
  File "mxnet/_ffi/_cython/./function.pxi", line 188, in mxnet._ffi._cy3.core.FunctionBase.__call__
  File "mxnet/_ffi/_cython/./function.pxi", line 133, in mxnet._ffi._cy3.core.FuncCall
  File "mxnet/_ffi/_cython/./base.pxi", line 90, in mxnet._ffi._cy3.core.CALL
mxnet.base.MXNetError: Traceback (most recent call last):
  File "../src/imperative/./imperative_utils.h", line 251
MXNetError: Check failed: outputs[i]-&gt;dtype() == out_types[i] (0 vs. 1) : 0-th output has invalid dtype. Expecting 1 got 0 in operator _npi_uniform
&gt;&gt; npx.set_np(dtype = False)
&gt;&gt; np.random.uniform(low = -1, high = 1, size = (5), out = a)
[0.09762704 0.18568921 0.43037868 0.6885315  0.20552671]
&lt;NDArray 5 &lt;denchmark-link:https://github.com/cpu&gt;@cpu&lt;/denchmark-link&gt;
(0)&gt;


So, I think I'd better not to set dtype=True flag in npx.set_np(), seperate this flag along in a single function npx.set_numpy_default_dtype() instead. Or if there any other better solutions, please tell me.

â€”
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub&lt;&lt;denchmark-link:https://github.com/apache/incubator-mxnet/issues/18193#issuecomment-621577944&gt;#18193 (comment)&lt;/denchmark-link&gt;
&gt;, or unsubscribe&lt;&lt;denchmark-link:https://github.com/notifications/unsubscribe-auth/ABHQH3R5XJLVP76L7A6LBD3RPDP5VANCNFSM4MT3GKPQ&gt;https://github.com/notifications/unsubscribe-auth/ABHQH3R5XJLVP76L7A6LBD3RPDP5VANCNFSM4MT3GKPQ&lt;/denchmark-link&gt;
&gt;.
		</comment>
		<comment id='10' author='sxjscience' date='2020-05-20T21:58:48Z'>
		should be resolved by &lt;denchmark-link:https://github.com/apache/incubator-mxnet/pull/18200&gt;#18200&lt;/denchmark-link&gt;

		</comment>
	</comments>
</bug>