<bug id='10592' author='cheyang' open_date='2019-12-08T23:56:00Z' closed_time='2020-02-07T09:29:52Z'>
	<summary>NPE in alluxio fuse log</summary>
	<description>
Alluxio Version:
What version of Alluxio are you using?
2.2.0
Describe the bug
Check the fuse log:
&lt;denchmark-code&gt;019-12-08 23:51:14,478 ERROR AlluxioFuseFileSystem - Failed to get info of /
com.google.common.util.concurrent.UncheckedExecutionException: java.lang.NullPointerException
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2050)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3952)
	at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4871)
	at alluxio.client.file.MetadataCache.getStatus(MetadataCache.java:56)
	at alluxio.client.file.BaseFileSystem.getStatus(BaseFileSystem.java:323)
	at alluxio.client.file.BaseFileSystem.getStatus(BaseFileSystem.java:313)
	at alluxio.fuse.AlluxioFuseFileSystem.getattr(AlluxioFuseFileSystem.java:374)
	at ru.serce.jnrfuse.AbstractFuseFS.lambda$init$1(AbstractFuseFS.java:95)
	at jnr.ffi.provider.jffi.NativeClosureProxy$$impl$$0.invoke(Unknown Source)
Caused by: java.lang.NullPointerException
	at java.util.concurrent.ConcurrentHashMap.putVal(ConcurrentHashMap.java:1011)
	at java.util.concurrent.ConcurrentHashMap.putIfAbsent(ConcurrentHashMap.java:1535)
	at alluxio.collections.ConcurrentHashSet.addIfAbsent(ConcurrentHashSet.java:72)
	at alluxio.client.file.MetadataCache.lambda$getStatus$0(MetadataCache.java:59)
	at com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:4876)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3528)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2277)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2154)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2044)
	... 8 more
&lt;/denchmark-code&gt;

To Reproduce
Steps to reproduce the behavior (as minimally and precisely as possible)
Expected behavior
A clear and concise description of what you expected to happen.
Urgency
Describe the impact and urgency of the bug.
Additional context
Add any other context about the problem here.
	</description>
	<comments>
		<comment id='1' author='cheyang' date='2019-12-12T00:05:09Z'>
		&lt;denchmark-link:https://github.com/cheyang&gt;@cheyang&lt;/denchmark-link&gt;
 based on the stacktrace, it's not the latest master branch I think.
		</comment>
		<comment id='2' author='cheyang' date='2020-02-06T23:46:41Z'>
		&lt;denchmark-link:https://github.com/apc999&gt;@apc999&lt;/denchmark-link&gt;
 please link fix if this is addressed.
		</comment>
		<comment id='3' author='cheyang' date='2020-02-07T09:26:38Z'>
		I'm not able to reproduce it, so close it. Will reopen it if I can reproduce.
		</comment>
	</comments>
</bug>