{"BR": {"BR_id": "5728", "BR_author": "bartvdbraak", "BRopenT": "2020-07-08T13:37:03Z", "BRcloseT": "2020-07-09T20:11:14Z", "BR_text": {"BRsummary": "NoneType uncallable on spacy.load('fr') (if self.is_base_form(univ_pos, morphology))", "BRdescription": "\n <denchmark-h:h2>How to reproduce the behaviour</denchmark-h>\n \n I am trying to get lemmatization/stemming to work with spaCy and spaCy_lefff in French. However, everytime I try to execute this code block in iPython kernel (jupyter notebook):\n <denchmark-code>import spacy\n nlp = spacy.load(\"fr\")\n \n doc = nlp(\"C'est une phrase.\")\n print([(w.text, w.pos_) for w in doc])\n </denchmark-code>\n \n I am getting the following error:\n <denchmark-code>---------------------------------------------------------------------------\n TypeError                                 Traceback (most recent call last)\n  in \n       2 nlp = spacy.load(\"fr_core_news_sm\")\n       3 \n ----> 4 doc = nlp(\"C'est une phrase.\")\n       5 print([(w.text, w.pos_) for w in doc])\n \n ~/anaconda3/lib/python3.7/site-packages/spacy/language.py in __call__(self, text, disable, component_cfg)\n     447             if not hasattr(proc, \"__call__\"):\n     448                 raise ValueError(Errors.E003.format(component=type(proc), name=name))\n --> 449             doc = proc(doc, **component_cfg.get(name, {}))\n     450             if doc is None:\n     451                 raise ValueError(Errors.E005.format(name=name))\n \n pipes.pyx in spacy.pipeline.pipes.Tagger.__call__()\n \n pipes.pyx in spacy.pipeline.pipes.Tagger.set_annotations()\n \n morphology.pyx in spacy.morphology.Morphology.assign_tag_id()\n \n morphology.pyx in spacy.morphology.Morphology.lemmatize()\n \n ~/anaconda3/lib/python3.7/site-packages/spacy/lang/fr/lemmatizer.py in __call__(self, string, univ_pos, morphology)\n      47             return [self.lookup(string)]\n      48         # See Issue #435 for example of where this logic is requied.\n ---> 49         if self.is_base_form(univ_pos, morphology):\n      50             return list(set([string.lower()]))\n      51         index_table = self.lookups.get_table(\"lemma_index\", {})\n \n TypeError: 'NoneType' object is not callable\n </denchmark-code>\n \n I have downloaded with python -m spacy download fr and python -m spacy download fr_core_news_sm.\n <denchmark-h:h2>Your Environment</denchmark-h>\n \n <denchmark-h:h2>Info about spaCy</denchmark-h>\n \n \n \n spaCy version: 2.3.1\n \n \n Platform: Linux-5.3.0-62-generic-x86_64-with-debian-buster-sid\n \n \n Python version: 3.7.6\n \n \n Models: fr, en\n \n \n Environment Information: iPython kernel, Jupyter Notebook, Anaconda3\n \n \n <denchmark-h:h2>Extra</denchmark-h>\n \n I have downloaded with python -m spacy download fr and python -m spacy download fr_core_news_sm.\n Extra info:\n <denchmark-code>\u276f python -m spacy validate\n \u2714 Loaded compatibility table\n \n ====================== Installed models (spaCy v2.3.1) ======================\n \u2139 spaCy installation:\n /home/bart/anaconda3/lib/python3.7/site-packages/spacy\n \n TYPE      NAME              MODEL             VERSION                            \n package   fr-core-news-sm   fr_core_news_sm   2.3.0   \u2714\n package   en-core-web-sm    en_core_web_sm    2.3.1   \u2714\n link      fr                fr_core_news_sm   2.3.0   \u2714\n link      en                en_core_web_sm    2.3.1   \u2714\n \n \u276f python -m spacy info\n \n ============================== Info about spaCy ==============================\n \n spaCy version    2.3.1                         \n Location         /home/bart/anaconda3/lib/python3.7/site-packages/spacy\n Platform         Linux-5.3.0-62-generic-x86_64-with-debian-buster-sid\n Python version   3.7.6                         \n Models           fr, en\n </denchmark-code>\n \n The english package does work however:\n <denchmark-code>import spacy\n nlp = spacy.load(\"en\")\n \n doc = nlp(\"Just a phrase.\")\n print([(w.text, w.pos_) for w in doc])\n </denchmark-code>\n \n with output\n <denchmark-code>[('Just', 'ADV'), ('a', 'DET'), ('phrase', 'NOUN'), ('.', 'PUNCT')]\n </denchmark-code>\n \n \t"}, "comments": {"comments_0": {"comment_id": 1, "comment_author": "bartvdbraak", "commentT": "2020-07-08T15:35:18Z", "comment_text": "\n \t\tThanks for the report!\n I can fix the bug so this code works as before, but I think the French lemmatizer is unintentionally using English-specific code here that doesn't make sense for French. Let me check the details first, but I think we can probably just remove this whole function.\n \t\t"}, "comments_1": {"comment_id": 2, "comment_author": "bartvdbraak", "commentT": "2020-07-08T15:37:38Z", "comment_text": "\n \t\tI'm having the exact same problem with the french model, whereas my script worked fine yesterday.\n I tried all 3 french models and there was the same error message TypeError: 'NoneType' object is not callable\n The English model works for me as well.\n Is there an update on the french models today that is causing the problem ?\n \t\t"}, "comments_2": {"comment_id": 3, "comment_author": "bartvdbraak", "commentT": "2020-07-08T15:40:52Z", "comment_text": "\n \t\tThe bug is in spacy v2.3.1. If you downgrade to v2.3.0 it should work. The models haven't changed (and won't need to change, the bug is in spacy itself).\n \t\t"}, "comments_3": {"comment_id": 4, "comment_author": "bartvdbraak", "commentT": "2020-07-09T12:09:08Z", "comment_text": "\n \t\tThanks, I will downgrade to version 2.3.0 for the time being, and hopefully your fix will be in the newest version soon :).\n \t\t"}, "comments_4": {"comment_id": 5, "comment_author": "bartvdbraak", "commentT": "2020-07-09T15:07:21Z", "comment_text": "\n \t\tHello,\n I am sorry, I just got the same issue today with the French package 2.3.0 today, while it works perfectly with English package 2.3.1 and Japanese package 2.3.2.\n Typing:\n import fr_core_news_sm\n nlpf = fr_core_news_sm.load()\n texte3= \"J'aime le vin blanc. \u00bb\n doc3= nlpf(texte3)\n <denchmark-h:h2>I get:</denchmark-h>\n \n TypeError                                 Traceback (most recent call last)\n  in \n ----> 1 doc3= nlpf(texte3)\n ~/opt/anaconda3/lib/python3.7/site-packages/spacy/language.py in call(self, text, disable, component_cfg)\n 447             if not hasattr(proc, \"call\"):\n 448                 raise ValueError(Errors.E003.format(component=type(proc), name=name))\n --> 449             doc = proc(doc, **component_cfg.get(name, {}))\n 450             if doc is None:\n 451                 raise ValueError(Errors.E005.format(name=name))\n pipes.pyx in spacy.pipeline.pipes.Tagger.call()\n pipes.pyx in spacy.pipeline.pipes.Tagger.set_annotations()\n morphology.pyx in spacy.morphology.Morphology.assign_tag_id()\n morphology.pyx in spacy.morphology.Morphology.lemmatize()\n ~/opt/anaconda3/lib/python3.7/site-packages/spacy/lang/fr/lemmatizer.py in (self, string, univ_pos, morphology)\n 47             return [self.lookup(string)]\n 48         # See Issue <denchmark-link:https://github.com/explosion/spaCy/issues/435>#435</denchmark-link>\n  for example of where this logic is requied.\n ---> 49         if self.is_base_form(univ_pos, morphology):\n 50             return list(set([string.lower()]))\n 51         index_table = self.lookups.get_table(\"lemma_index\", {})\n TypeError: 'NoneType' object is not callable\n \t\t"}, "comments_5": {"comment_id": 6, "comment_author": "bartvdbraak", "commentT": "2020-07-09T15:17:05Z", "comment_text": "\n \t\tThe problem is not the model version, it is the spacy version. Try downgrading to spacy==2.3.0 temporarily. We will have a fix in a new version of spacy soon, which should be 2.3.2.\n \t\t"}}}, "commit": {"commit_id": "923affd091dac4c1a7e11168f7c8f1f05dcc224e", "commit_author": "Adriane Boyd", "commitT": "2020-07-09 22:11:13+02:00", "changed_files": {"file_0": {"file_change_type": "MODIFY", "file_Nmethod": 2, "file_old_name": "spacy\\lang\\fr\\lemmatizer.py", "file_new_name": "spacy\\lang\\fr\\lemmatizer.py", "hunks": {"hunk_0": {"Ismethod": 1, "added_lines": null, "deleted_lines": "48,49,50", "method_info": {"method_name": "__call__", "method_params": "self,string,univ_pos,morphology", "method_startline": "20", "method_endline": "60"}}, "hunk_1": {"Ismethod": 1, "added_lines": null, "deleted_lines": "62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97", "method_info": {"method_name": "is_base_form", "method_params": "self,univ_pos,morphology", "method_startline": "62", "method_endline": "97"}}}}}}}