<bug id='521' author='znation' open_date='2018-04-12T09:54:40Z' closed_time='2018-04-12T23:47:36Z'>
	<summary>vg2svg, vg2png not packaged in wheel artifact</summary>
	<description>
Repro steps + error:
(base) âžœ  ~ ipython
Python 3.6.4 |Anaconda, Inc.| (default, Jan 16 2018, 12:04:33) 
Type 'copyright', 'credits' or 'license' for more information
IPython 6.3.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import turicreate as tc

In [2]: sf = tc.SFrame.read_csv('https://docs-assets.developer.apple.com/turicreate/datasets/tc-clang-format-results.csv')
Downloading https://docs-assets.developer.apple.com/turicreate/datasets/tc-clang-format-results.csv to /var/tmp/turicreate-zach/55212/7f92c149-b210-4f78-a386-82035304e9ab.csv
Finished parsing file https://docs-assets.developer.apple.com/turicreate/datasets/tc-clang-format-results.csv
Parsing completed. Parsed 100 lines in 0.128734 secs.
------------------------------------------------------
Inferred types from first 100 line(s) of file as 
column_type_hints=[int,int,str,int,str,str,str,str,str,str,str,str,str,str,str,str,str,str,str,str,str,str,str]
If parsing fails due to incorrect types, you can correct
the inferred type list above and pass it to read_csv in
the column_type_hints argument
------------------------------------------------------
Finished parsing file https://docs-assets.developer.apple.com/turicreate/datasets/tc-clang-format-results.csv
Parsing completed. Parsed 10000 lines in 0.067388 secs.

In [3]: plt = tc.visualization.columnwise_summary(sf)
Materializing SFrame...
Done.

In [4]: plt.save('/Users/zach/Desktop/temp.svg')
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
&lt;ipython-input-4-6e54fd94c208&gt; in &lt;module&gt;()
----&gt; 1 plt.save('/Users/zach/Desktop/temp.svg')

~/miniconda3/lib/python3.6/site-packages/turicreate/visualization/_plot.py in save(self, filepath)
    176             else:
    177                 # something else
--&gt; 178                 raise RuntimeError(stderr)
    179             # delete temp file that user didn't ask for
    180             _run_cmdline("rm " + temp_file_path)

RuntimeError: b"module.js:549\n    throw err;\n    ^\n\nError: Cannot find module '/Users/zach/miniconda3/lib/python3.6/site-packages/turicreate/vg2svg'\n    at Function.Module._resolveFilename (module.js:547:15)\n    at Function.Module._load (module.js:474:25)\n    at Function.Module.runMain (module.js:693:10)\n    at startup (bootstrap_node.js:188:16)\n    at bootstrap_node.js:609:3\n"
	</description>
	<comments>
		<comment id='1' author='znation' date='2018-04-12T23:47:35Z'>
		Great find, thank you for pointing this out! Fixed by &lt;denchmark-link:https://github.com/apple/turicreate/pull/526&gt;#526&lt;/denchmark-link&gt;

		</comment>
	</comments>
</bug>